### PR TITLE
Added pSMAD3 for Human Lung

### PR DESCRIPTION
**Pull request by Rosa-234**
I've added staining conditions for pSMAD3 antibody (in human lung FFPE).

### CODE REVIEW

**Review by radtkea — COMMENTED** [review]
Thanks so much Rosa! Looks good but a few comments below. 

Markdown file notes: Observed is misspelled. 
CSV file: Define IPF in csv file.

Will you also include the antibody from CST that you do not recommend?

@zivy Will you also review @Rosa-234 work? Thanks all!

**Comment by zivy** [comment]
Hello @radtkea, @Rosa-234,

The original PR failed the automated testing, so I addressed all the issues. Please take a look and confirm that all looks good. 

@radtkea, once you approve I will merge.

**Comment by Rosa-234** [comment]
Hi @zivy, thank you for fixing all the issues!

**Comment by zivy** [comment]
Hello @Rosa-234,

Thanks for the contribution. You are now listed on our [contributors page](https://ibeximagingcommunity.github.io/ibex_imaging_knowledge_base/the_who.html) and will appear on the author byline when we make our next authoritative release [on zenodo](https://doi.org/10.5281/zenodo.7693278).

**Pull request merged**
